version: "3.7"
services:
  rbox1:
    image: rqlite/rqlite
    hostname: rbox1
    restart: always
    entrypoint:
      - rqlited 
      - -http-addr
      - "rbox1:4001"
      - -raft-addr
      - "rbox1:4002"
      - -raft-adv-addr
      - "rbox1:4002"
      - -raft-timeout
      - 5s
      - -raft-election-timeout
      - 5s
      - /rqlite/file/data1
    ports:
      - "4001:4001"
      - "4002:4002"
    volumes:
      - .:/host

  rbox2:
    image: rqlite/rqlite
    hostname: rbox2
    restart: always
    entrypoint:
      - rqlited 
      - -http-addr
      - "rbox2:4011"
      - -raft-addr
      - "rbox2:4012"
      - -raft-adv-addr
      - "rbox2:4012"
      - -raft-timeout
      - 5s
      - -raft-election-timeout
      - 5s
      - -join 
      - http://rbox1:4001
      - /rqlite/file/data2
    depends_on:
      - rbox1
    ports:
      - "4011:4011"
      - "4012:4012"
    volumes:
      - .:/host

  rbox3:
    image: rqlite/rqlite
    hostname: rbox3
    restart: always
    entrypoint:
      - rqlited 
      - -http-addr
      - "rbox3:4021"
      - -raft-addr
      - "rbox3:4022"
      - -raft-timeout
      - 5s
      - -raft-election-timeout
      - 5s
      - -join 
      - http://rbox1:4001
      - /rqlite/file/data3
    depends_on:
      - rbox1
    ports:
      - "4021:4021"
      - "4022:4022"
    volumes:
      - .:/host


networks:
  default:
    #driver: bridge 
    name: rqlite-network
    #external:
    #  name: rqlite-network
    #networks:
    #  default:
    #      external:
