version: "3.7"
services:
  client:
    image: golang:alpine
    hostname: gobox
    restart: always
    stdin_open: true
    tty: true
    entrypoint:
      - /bin/sh
    volumes:
      - .:/host

  nginx:
    image: nginx:1.17.2-alpine
    volumes:
      - ./nginx/forward_proxy.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
    ports:
      - "8888:8888"

  rbox1:
    image: rqlite/rqlite
    hostname: rbox1
    restart: always
    entrypoint:
      - rqlited 
      - -http-addr
      - "rbox1:4001"
      - -raft-addr
      - "rbox1:4002"
      - -raft-adv-addr
      - "rbox1:4002"
      - -raft-timeout
      - 5s
      - -raft-election-timeout
      - 5s
      - /rqlite/file/data1
    volumes:
      - .:/host

  rbox2:
    image: rqlite/rqlite
    hostname: rbox2
    restart: always
    entrypoint:
      - rqlited 
      - -http-addr
      - "rbox2:4001"
      - -raft-addr
      - "rbox2:4002"
      - -raft-adv-addr
      - "rbox2:4002"
      - -raft-timeout
      - 5s
      - -raft-election-timeout
      - 5s
      - -join 
      - http://rbox1:4001
      - /rqlite/file/data2
    depends_on:
      - rbox1
    volumes:
      - .:/host

  rbox3:
    image: rqlite/rqlite
    hostname: rbox3
    restart: always
    entrypoint:
      - rqlited 
      - -http-addr
      - "rbox3:4001"
      - -raft-addr
      - "rbox3:4002"
      - -raft-timeout
      - 5s
      - -raft-election-timeout
      - 5s
      - -join 
      - http://rbox1:4001
      - /rqlite/file/data3
    depends_on:
      - rbox1
      - rbox2
    volumes:
      - .:/host


networks:
  default:
    #driver: bridge 
    name: rqlite-network
    #external:
    #  name: rqlite-network
    #networks:
    #  default:
    #      external:
