// generated by dbgen ; DO NOT EDIT

package main

import (
	"time"
)

//
// testStruct DBObject generator
//
func (o testStruct) NewObj() interface{} {
	return new(testStruct)
}

//
// testStruct DBObject interface functions
//
func (o *testStruct) InsertValues() []interface{} {
	return []interface{}{o.Name, o.Kind, o.Data, o.Modified}
}

func (o *testStruct) UpdateValues() []interface{} {
	return []interface{}{o.Name, o.Kind, o.Data, o.Modified, o.ID}
}

func (o *testStruct) MemberPointers() []interface{} {
	return []interface{}{&o.ID, &o.Name, &o.Kind, &o.Data, &o.Modified}
}

func (o *testStruct) Key() int64 {
	return o.ID
}

func (o *testStruct) SetID(id int64) {
	o.ID = id
}

func (o *testStruct) TableName() string {
	return "structs"
}

func (o *testStruct) SelectFields() string {
	return "id,name,kind,data,modified"
}

func (o *testStruct) InsertFields() string {
	return "id,name,kind,data,modified"
}

func (o *testStruct) KeyField() string {
	return "id"
}

func (o *testStruct) KeyName() string {
	return "ID"
}

func (o *testStruct) Names() []string {
	return []string{"Name", "Kind", "Data", "Modified"}
}

func (o *testStruct) ModifiedBy(user int64, t time.Time) {
}
